server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ecommerce?currentSchema=${DB_SCHEMA}}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    open-in-view: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: ${DB_SCHEMA}

  batch:
    jdbc:
      initialize-schema: always

    job:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

  endpoint:
    health:
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: ${OTEL_ENDPOINT:http://localhost:4320/v1/traces}

  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

      percentiles:
        http.server.requests: 0.5,0.95,0.99

    tags:
      application: payment-service

logging:
  level:
    org.hibernate.SQL: INFO
  file:
    name: logs/payment-service.log

springdoc:
  show-actuator: true