{
 "title": "Loki Logs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Live Logs Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"payment-service\"}"
    }
   ]
  },
  {
   "title": "ERROR logs/sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {service_name=\"payment-service\"}\r\n      | json\r\n      | level=\"ERROR\"\r\n    [1m]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "WARN logs/sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {service_name=\"payment-service\"}\r\n      | json\r\n      | level=\"WARN\"\r\n    [1m]\r\n  )\r\n)"
    }
   ]
  }
 ]
}