replicaCount: 1

image:
  repository: payment-service
  tag: "3.0"
  pullPolicy: Never

service:
  port: 8082
  type: ClusterIP

configMapName: payment-configmap-uat
secretName: payment-secret-uat

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10

  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 10
    periodSeconds: 5