apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: payment-service

  template:
    metadata:
      labels:
        app: payment-service

    spec:
      containers:
        - name: payment-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: APP_ENV

            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: SPRING_PROFILES_ACTIVE

            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: DB_URL

            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: DB_USERNAME

            - name: OTEL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: OTEL_ENDPOINT

            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: DB_SCHEMA

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DB_PASSWORD

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.port }}

            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.port }}

            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}